AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRailsVersion: 5.1

Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: space
  Enabled: true

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SaveBang:
  Enabled: false

Rails/TimeZone:
  EnforcedStyle: strict
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true
  EnforcedStyle: assign_to_condition

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/NegatedIf:
  Enabled: false

Style/NumericLiterals:
  Enabled: true
  Strict: true

Style/ReturnNil:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

Style/GuardClause:
  Enabled: false
