default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: null_pointer_exception_development

test:
  <<: *default
  database: null_pointer_exception_test

production:
  <<: *default
  database: null_pointer_exception_production
  username: username
  password: <%= ENV['NULL_POINTER_EXCEPTION_DATABASE_PASSWORD'] %>
